.TH fuzzytime 1 "January 21, 2011" "version 0.6" "A fuzzy clock and timer"

.\" -------------------------------------------------------------------------------------

.SH NAME
fuzzytime \- a clock and timer that tell the time in a more familiar way

.\" -------------------------------------------------------------------------------------

.SH SYNOPSIS
.B fuzzytime
COMMAND [OPTIONS]

.\" -------------------------------------------------------------------------------------

.SH DESCRIPTION
Humans tend to be much more casual than computers when it comes to telling the time. The computers’ usual "22:15"-format requires a little extra processing as compared to the more familiar "quarter past ten".
.PP
fuzzytime attempts to remove this obstacle by telling you the time the way that a human would.
.PP
fuzzytime is neither the first nor the only program which can do this, but it hopes to get closer to the goal than others because the author is a linguist and expects that this should help him come up with localizations which do not sound like MS® Translator. Besides, it also has the timer mode which can be very handy.

.\" -------------------------------------------------------------------------------------

.SH INTENDED USE
The intended use for fuzzytimer is in an environment which does not provide a status bar with a built-in clock. It is expected to be piped to a status bar and run every minute or so in the clock mode.
.PP
The timer can be set via the timer-setting mode. When the timer is set, the clock mode will show how much time there is left till some event. To get back to showing the actual time, timer has to be unset.

.\" -------------------------------------------------------------------------------------

.SH OPTIONS
.SS Modes
.TP
There are two: time-showing (clock) and timer-setting (timer). The name of the mode has to be put after the program name in the invocation, and before the options.

.SS Clock mode (print the time)
.TP
\-c \--clock
12 or 24-hour clock (22:00 -> "ten" or "twenty-two"); the default is 12.
.TP
\-l \--lang
Language; currently Danish (da), English (en), French (fr), German (de) and Polish (pl); the default is en.
.TP
\-p \--prec
Precision; should be between 1 and 60 [minutes]; the default is 5.
.TP
\-t \--time
Time to fuzzify as HH:MM; the default is the current time.
.TP
\-s \--style
How the time is told; see below; the default is 1.
.TP
\-? \--help
Display help message
.TP
\-V \--version
Print version information

.SS Timer mode (set the timer)
.TP
END
The time to set the timer to count down to, as HH:MM; this is obligatory and there is no default. To unset the timer, END must be "unset".

.\" -------------------------------------------------------------------------------------

.SH EXAMPLES
.TP
Print the current time in Polish in 12-hour clock, with 10-minute precision, in style 2.
.B fuzzytime clock
\-lpl -p10 -s2
.PP
.TP
Print 23:50 in German in 24-hour clock, with 1-minute precision, in style 1.
.B fuzzytime clock
\-c24 -lde -p1 -t23:50
.PP
.TP
Set the timer to count down to 12:30 (showing the time will be disabled).
.B fuzzytime timer
12:30
.PP
.TP
Unset the timer (re-enable showing the time).
.B fuzzytime timer
unset

.\" -------------------------------------------------------------------------------------

.SH STYLES
In many languages, the time can be told in at least a few ways. E.g., in English the words "midnight" and "noon" can be used, the numerals "twenty-four" and "twelve" or "twelve" for both cases. The latter distinction is taken care of by --clock. The former – by --style. Currently, two styles are available. See LANGUAGES below for details.

As of now, styles are not available (= the setting is ignored) in the timer mode.

.\" -------------------------------------------------------------------------------------

.SH LANGUAGES

.SS Comparison
                                                       halves
              midnight  noon    half   quarter  hour    base 

Danish (M_ller + KS)
                 –        –       +       +      –       –

Dutch (thanks litemotiv)
    style 1      –        –       +       +     [0]      –
    style 2    [≠ 30]     –       +       +     [0]    [±10]

English (KS)
    style 1      –        –       +       +      –       –
    style 2      +        +       +       +      –       –

French (KS)
    style 1      –        –       +       +      +       –
    style 2      +        +       +       +      +       –

German (KS)
    style 1      –        –       +       +     [0]      –
    style 2    [≠ 30]     –       +       +     [0]     [±7]

Greek (thanks Gbak)
                 –        –       +       +      –       –

Polish (KS)
    style 1      –        –       +       +      –       –
    style 2    [≠ 30]     –       +       +      –      [±7]

Turkish (KS)
    style 1      –        –       +       + [0, 12:30]   –
    style 2      –        –       +       + [0, 12:30] [±10]

.SS Notes

midnight, noon: the words "midnight" and "noon" are used; [≠ 30]: the word is used except for halves.

half, quarter: min % 15 = 0 is treated as a special case.

hour: the word "hour" is used; [0]: the word is only used for round hours; [0, 12:30]: the word is only used for round hours, 12:30 and 0:30.

halves base: min in a certain range around 30 is referred to half hours rather than to full ones.

.SS Examples

Danish

11:45 = 23:45 = kvart i tolv.


Dutch

Style 1: 11:45 = 23:45 = kwart voor twaalf.

Style 2: 11:30 = half twaalf, 11:45 = kwart voor twaalf, 23:30 = half twaalf, 23:45 = kwart voor middernacht, 10:20 = tien voor half elf


English

Style 1: 11:45 = 23:45 = quarter to twelve.

Style 2: 11:45 = quarter to noon, 23:45 = quarter to midnight.

Timer: 90 = in an hour and a half, 15 = in a quarter, -20 = ! a quarter ago !


French

Style 1: 11:45 = 23:45 = douze heures moins le quart.

Style 2: 11:45 = midi moins le quart, 23:30 = onze heures et demie, 23:45 = minuit moins le quart.


German

Style 1: 11:45 = 23:45 = Viertel vor zwölf.

Style 2: 11:30 = halb zwölf, 11:45 = Viertel vor zwölf, 23:30 = halb zwölf, 23:45 = Viertel vor Mitternacht, 10:25 = fünf vor halb elf.


Greek

11:45 = 23:45 = δώδεκα παρά τέταρτο


Polish

Style 1: 11:45 = 23:45 = za kwadrans dwunasta.

Style 2: 11:30 = w pół do dwunastej; 11:45 = za kwadrans dwunasta, 23:30 = w pół do dwunastej, 23:45 = za kwadrans północ, 10:25 = za pięć w pół do jedenastej.


Turkish

Style 1: 11:45 = 23:45 = on ikiye çeyrek var.

Style 2: 12:00 = saat on iki, 12:30 = saat yarım, 11:20 = on bir buçuğa on var, 12:25 = on iki buçuğa beş var.

.\" -------------------------------------------------------------------------------------

.SH DEPENDS
(Arch Linux) ghc, haskell-cmdargs

.\" -------------------------------------------------------------------------------------

.SH BUGS
No known bugs at this time.

.\" -------------------------------------------------------------------------------------

.SH AUTHOR
Kamil Stachowski (kamil.stachowski@gmail.com)

Thanks are due to:

Daniel Fischer and Brent Yorger from beginners@haskell.org for Haskell help.

Gbak from bbs.archlinux.org for the Greek translation.

litemotiv from bbs.archlinux.org for the Dutch translation.

M_ller from bbs.archlinux.org for the Danish translation and most of the implementation.
