.TH fuzzytime 1 "January 15, 2011" "version 0.4" "A clock that tells the time in a more familiar way"

.\" -------------------------------------------------------------------------------------

.SH NAME
fuzzytime \- a clock that tells the time in a more familiar way

.\" -------------------------------------------------------------------------------------

.SH SYNOPSIS
.B fuzzytime
[OPTIONS]

.\" -------------------------------------------------------------------------------------

.SH DESCRIPTION
Humans tend to be much more casual than computers when it comes to telling the time. The computers’ usual "22:15"-format requires a little extra processing as compared to the more familiar "quarter past ten".
.PP
fuzzytime attempts to remove this obstacle by telling you the time the way that a human would.
.PP
fuzzytime is neither the first nor the only program which can do this, but it hopes to get closer to the goal than others because the author is a linguist and expects that this should help him come up with localizations which do not sound like MS® Translator.

.\" -------------------------------------------------------------------------------------

.SH OPTIONS
.TP
\-c \--clock
12 or 24-hour clock (22:00 -> "ten" or "twenty-two"); the default is 12.
.TP
\-l \--lang
Language; currently Danish (da), English (en), French (fr), German (de) and Polish (pl); the default is en.
.TP
\-p \--prec
Precision; should be between 1 and 60 [minutes]; the default is 5.
.TP
\-t \--time
Time to fuzzify as HH:MM; the default is the current time.
.TP
\-s \--style
How the time is told; see below; the default is 1.
.TP
\-? \--help
Display help message
.TP
\-V \--version
Print version information

.\" -------------------------------------------------------------------------------------

.SH EXAMPLES
.TP
Print the current time in Polish in 12-hour clock, with 10-minute precision, in style 2.
.B fuzzytime
\-lpl -p10 -s2
.PP
.TP
Print 23:50 in German in 24-hour clock, with 1-minute precision, in style 1.
.B fuzzytime
\-c24 -lde -p1 -t23:50

.\" -------------------------------------------------------------------------------------

.SH STYLES
In many languages, the time can be told in at least a few ways. E.g., in English the words "midnight" and "noon" can be used, the numerals "twenty-four" and "twelve" or "twelve" for both cases. The latter distinction is taken care of by --clock. The former – by --style. Currently, two styles are available. See LANGUAGES below for details.

.\" -------------------------------------------------------------------------------------

.SH LANGUAGES

.SS Comparison
              midnight  noon    half   quarter  hour   halves
                                                        base

Danish (M_ller + KS)
    style 1      –        –       +       +      –       –
    style 2      +     [0, 30]    +       +      –       –

Dutch (thanks litemotiv)
    style 1      –        –       +       +     [0]      –
    style 2    [≠ 30]     –       +       +     [0]    [±10]

English (KS)
    style 1      –        –       +       +      –       –
    style 2      +        +       +       +      –       –

German (KS)
    style 1      –        –       +       +     [0]      –
    style 2    [≠ 30]     –       +       +     [0]     [±7]

French (KS)
    style 1      –        –       +       +      +       –
    style 2      +        +       +       +      +       –

Polish (KS)
    style 1      –        –       +       +      –       –
    style 2    [≠ 30]     –       +       +      –      [±7]

.SS Notes

midnight, noon: the words "midnight" and "noon" are used; [≠ 30] means that the word used but for halves.

half, quarter: min % 15 = 0 is treated as a special case

hour: the word "hour" is used; [0] means that the word is only used for round hours

halves base: min in a certain range around 30 is referred to half hours rather than to full ones

.SS Examples

Danish

Style 1: 11:45 = 23:45 = kvart i tolv.

Style 2: 11:30 = halv aften, 11:45 = kvart i tolv, 23:45 = kvart i midnat.


Dutch

Style 1: 11:45 = 23:45 = kwart voor twaalf.

Style 2: 11:30 = half twaalf, 11:45 = kwart voor twaalf, 23:30 = half twaalf, 23:45 = kwart voor middernacht, 10:20 = tien voor half elf


English

Style 1: 11:45 = 23:45 = quarter to twelve.

Style 2: 11:45 = quarter to noon, 23:45 = quarter to midnight.


German

Style 1: 11:45 = 23:45 = Viertel vor zwölf.

Style 2: 11:30 = halb zwölf, 11:45 = Viertel vor zwölf, 23:30 = halb zwölf, 23:45 = Viertel vor Mitternacht, 10:25 = fünf vor halb elf.


French

Style 1: 11:45 = 23:45 = douze heures moins le quart.

Style 2: 11:45 = midi moins le quart, 23:30 = onze heures et demie, 23:45 = minuit moins le quart.


Polish

Style 1: 11:45 = 23:45 = za kwadrans dwunasta.

Style 2: 11:30 = wpół do dwunastej; 11:45 = za kwadrans dwunasta, 23:30 = wpół do dwunastej, 23:45 = za kwadrans północ, 10:25 = za pięć wpół do jedenastej.

.\" -------------------------------------------------------------------------------------

.SH DEPENDS
(Arch Linux) cabal-install, ghc, haskell-cmdargs

.\" -------------------------------------------------------------------------------------

.SH BUGS
No known bugs at this time.

.\" -------------------------------------------------------------------------------------

.SH AUTHOR
Kamil Stachowski (kamil.stachowski@gmail.com)

Thanks are due to:

Daniel Fischer and Brent Yorger from beginners@haskell.org for Haskell help.

litemotiv from bbs.archlinux.org for the Dutch translation.

M_ller from bbs.archlinux.org for the Danish translation and most of the implementation.
